### ISSUE TITLE
How to add parsed variables to process.env

### ISSUE THREAD

**Issue by ghost** [niftylettuce/dotenv-parse-variables#1]
Is there a quick way to add the parsed variables to `process.env`, or do I have to create my own solution?

**Comment by ghost** [comment]
Nevermind, I just learned that all values in `process.env` are converted back to string anyway: http://stackoverflow.com/a/10265271/2306587

**Comment by richardaum** [comment]
Actually, there is a way. If you do process.env = { ...process.env, bla: true }
