### ISSUE TITLE
How to parse string with only numbers

### ISSUE THREAD

**Issue by MickL** [niftylettuce/dotenv-parse-variables#18]
If my .env has a variable that should be a string, but consists only of digits:

```
AWS_ACCESS_KEY_ID="123"
```

It will get parsed to number. How may I precent this? Are the quotation marks ignored?

**Comment by niftylettuce** [comment]
PR welcome!

**Comment by niftylettuce** [comment]
@MickL All you have to do is affix it with an asterisk.  Please see the README before opening issues.  Thanks.

**Comment by niftylettuce** [comment]
@MickL If there's an edge case you need help with specifically just pass it along - thank you and hope this helps!
