### ISSUE TITLE
Array with just one variable

### ISSUE THREAD

**Issue by MickL** [niftylettuce/dotenv-parse-variables#19]
Currently when creating an array with just one item, it creates an array of two:

```
CORS_ORIGINS=myurl.com,
=> ['myurl.com', '']
```

It would be nice to be able to create an array even if there is just one item.

**Comment by MickL** [comment]
@niftylettuce that was fast, thank you!

**Comment by niftylettuce** [comment]
Released to npm as v0.3.0

Thanks @MickL 

Ref: <https://github.com/niftylettuce/dotenv-parse-variables/releases/tag/v0.3.0>
