### ISSUE TITLE
Ignore functions in parsed config objects

### ISSUE THREAD

**Issue by jeremy303** [niftylettuce/dotenv-parse-variables#20]
Great library!

I'm using this with [react-native-config](https://github.com/luggit/react-native-config), which includes a helper function in its configuration object.  This function must first be manually stripped before passing the config to `dotenv-parse-variables`, otherwise it will throw an error: `TypeError: value.indexOf is not a function`.

As a convenience, it would be great if `dotenv-parse-variables` ignored any functions in the object being parsed.

Thanks!

**Comment by niftylettuce** [comment]
Could you submit a PR and possibly a test too? @HolySamosa

**Comment by jeremy303** [comment]
Sure thing @niftylettuce!

**Comment by niftylettuce** [comment]
fix will be released shortly

**Comment by niftylettuce** [comment]
v1.0.0 released <https://github.com/niftylettuce/dotenv-parse-variables/releases/tag/v1.0.0>
