### ISSUE TITLE
Empty string parsed as 0

### ISSUE THREAD

**Issue by emzet** [niftylettuce/dotenv-parse-variables#21]
https://github.com/niftylettuce/dotenv-parse-variables/blob/abd9a9f7499e6b09a8bd85435cfda84fe95937b3/src/index.js#L58-L61

**Comment by niftylettuce** [comment]
fix will be released shortly

**Comment by niftylettuce** [comment]
v1.0.0 released <https://github.com/niftylettuce/dotenv-parse-variables/releases/tag/v1.0.0>
