### ISSUE TITLE
Allow inline comments

### ISSUE THREAD

**Issue by bgausden** [niftylettuce/dotenv-parse-variables#24]
Looks like inline comments in .env aren't handled?

e.g a .env containing the following:

`LIMITER_MAX_CALL=50 # limit number of calls to this value per LIMITER_TIME_INTERVAL`

returns in env

```
{
  ...
  LIMITER_MAX_CALL="50 # limit number of calls to this value per LIMITER_TIME_INTERVAL"
  ...
}
```

Ideally everything from "#" onward should be stripped when parsing.

**Comment by niftylettuce** [comment]
sure I'll add this, one sec

**Comment by niftylettuce** [comment]
actually I don't want it to be breaking, so not going to add it for now.

PR welcome if you want to do it in a way that's super clean
