### ISSUE TITLE
Variables are not being assigned/parsed into process.env

### ISSUE THREAD

**Issue by iagoccampos** [niftylettuce/dotenv-parse-variables#26]
I'm probably doing something really wrong, but i can't find what...

```typescript
import dotenv from 'dotenv'
import dotenvParseVariables from 'dotenv-parse-variables'

let env = dotenv.config()
if (env.error || !env.parsed) throw env.error
env = dotenvParseVariables(env.parsed, { assignToProcessEnv: true, overrideProcessEnv: true })
console.log(process.env)
```

My .env file: 
```
PORT=3000
JWT_SECRET=token
```
What I got from process.env:
```js
{
  PORT: '3000', // String
  JWT_SECRET: 'token'
}
```
What I expect:
```js
{
  PORT: 3000, // Number
  JWT_SECRET: 'clinica'
}
```

What I'm doing wrong?

**Comment by niftylettuce** [comment]
If you can add a failing test in this repository and submit as a PR that'd be great

**Comment by Lautenschlager-id** [comment]
I think this issue is related to the fact that process.env will always transform its values into a string.

I've just tested this non-lib-related chunk
```JS
process.env["HI"] = 666;
console.log(process.env["HI"], typeof process.env["HI"]);
```

And for my surprise this is the output
![image](https://user-images.githubusercontent.com/26045253/166807900-2d6aee75-4509-4b25-93b4-6b6bffe0ec81.png)

**Comment by titanism** [comment]
You are correct, it will always be a String and cannot be overridden.  We assign the variables but you cannot rely on `process` unless you parse it each time using this library.
