### ISSUE TITLE
[fix] long string number parsed incorrectly

### ISSUE THREAD

**Issue by vmarinescu** [niftylettuce/dotenv-parse-variables#27]
## Describe the bug

**Node.js version:** 20

**Description:** Big numbers like "12345678901234567" are parsed incorrectly to number

## Actual behavior

"12345678901234567" becomes 1234567890123456**8** (number)

## Expected behavior

"12345678901234567" becomes 12345678901234567 (bigint)

or

"12345678901234567" stays as "12345678901234567" (string)

## Code to reproduce
.env:
ENV_VAR="12345678901234567"

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by titanism** [comment]
Please submit a PR, add tests, and contribute.
